# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0639170841c6ed7196330d9e7e2155920308265e25b94c80964c7399c5eb291e4edfccf049ae5fcfd7edd7c175416bd71558b5a7402bf71058dc4705b119c52
  azure_credentials:
    account_name: karaage
    access_key: VmSiEpfjnoZj/9LZIxv2XG6P5UZxhkLBa+McLzw1Azhc66xCKqKefhMTJA9MU/cH2ALXsiKq3wl1fMfT1zWW1g==

test:
  secret_key_base: 404b3fb63e2384bc64c50e23c295c9cace68eff94e7ef81063011ecc111f3371fd67562eefb599ed71d56848da38f26114f4db451924bf6c2aaeed6b20a3ab3b
  azure_credentials:
    account_name: karaage
    access_key: VmSiEpfjnoZj/9LZIxv2XG6P5UZxhkLBa+McLzw1Azhc66xCKqKefhMTJA9MU/cH2ALXsiKq3wl1fMfT1zWW1g==

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
